# Generated by Django 5.2.8 on 2025-11-12 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('director', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('users_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_views', models.IntegerField(blank=True, null=True)),
                ('total_likes', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('directors', models.ManyToManyField(blank=True, related_name='movies', to='director.director')),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='genre.genre')),
            ],
        ),
    ]
